package net.viperfish.minijava.scanner;

public enum TokenType {

    EOT, CLASS, ID, LEFT_LARGE_BRACKET, RIGHT_LARGE_BRACKET, SEMI_COLON, VOID, LEFT_PARANTHESIS, RIGHT_PARANTHESIS,
    PUBLIC, PRIVATE, STATIC, INT, BOOLEAN, LEFT_SQ_BRACKET, RIGHT_SQ_BRACKET, COMMA, THIS, DOT, RETURN, IF, ELSE,
    WHILE, OPERATOR, NUM, TRUE, FALSE, NEW, EQ, NULL

}
